  # Find all the available rules by running:
  # swiftlint rules
  # 
  # Pretty nice explanation of most useful rules: https://www.avanderlee.com/optimization/swiftlint-optin-rules

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - tools
  - GoogleMaps*
  - GooglePlaces*

opt_in_rules: # some rules are only opt-in
  - empty_count
  - empty_string
  - force_unwrapping
  - attributes
  - closure_end_indentation
  - closure_spacing
  - extension_access_modifier
  - first_where
  - implicit_return
  - joined_default_parameter
  - let_var_whitespace
  - multiline_parameters
  - nimble_operator
  - notification_center_detachment
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_super_call
  - quick_discouraged_call
  - redundant_nil_coalescing
  - single_test_class
  - syntactic_sugar
  - vertical_parameter_alignment_on_call
  - convenience_type
  - fatal_error_message
  - modifier_order
  - toggle_bool
  - fallthrough
  - unavailable_function

# redundant_string_enum_value ~
# file_length ~ in favor for correct access control (extensions in different
#               files require properties to be internal instead of private).
disabled_rules: # rule identifiers to exclude from running
  - redundant_string_enum_value
  - file_length
  - unused_closure_parameter
  - object_literal
  - large_tuple

# configurable rules can be customized from this configuration file
# binary rules can set their severity level

force_cast: warning

attributes:
  always_on_same_line: ["@IBAction", "@NSManaged", "@objc"]

force_try:
  severity: warning # explicitly

type_name:
  max_length:
    warning: 50
  min_length:
    warning: 3

cyclomatic_complexity:
  warning: 13
  error: 50

line_length: 140

type_body_length:
  warning: 300
  error: 1000

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 6
  error: 10

identifier_name:
  max_length:
    warning: 40
    error: 60
  min_length:
    warning: 1

nesting:
  type_level:
    warning: 2
    error: 5
  statement_level:
    warning: 3
    error: 5