require("user.core.options")
require("user.core.keymaps")
require("user.lazy")
-- require("plugins.comment")
-- require("plugins.nvim-tree")
-- require("plugins.telescope")
-- require("plugins.nvim-cmp")
-- require("plugins.lsp.mason")
-- require("plugins.lsp.lspsaga")
-- require("plugins.lsp.lspconfig")
-- require("plugins.lsp.null-ls")
-- require("plugins.autopairs")
-- require("plugins.treesitter")
-- require("plugins.gitsigns")